# -*- coding: utf-8 -*-
"""messey_customer_project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KT97ImrEXt0uNEKY-Xnr1UUSfj4HRSQ-
"""

!pip install fg-data-profiling pandas numpy --quiet

import pandas as pd
import numpy as np
import data_profiling
from data_profiling import ProfileReport
from google.colab import files

uploaded = files.upload()

df = pd.read_csv('messy_customer_orders.csv')

profile = ProfileReport(df, title = "Profiling Report", explorative = True)
profile.to_file('report.html')
files.download('report.html')

df.shape

df.dtypes

#missing values
df.isnull().sum()

df.head()

df.columns = (
    df.columns
    .str.replace(' ','_')
    .str.lower()
    .str.strip()
)

df.head(
10
)

n_dupes = df.duplicated().sum()



n_dupes

df[df.duplicated(keep = False)].sort_values(by = list(df.columns)).head(10)

df = df.drop_duplicates()

df.shape

#standardization
for col in ['category', 'status', 'country']:
    df[col] = df[col].str.strip().str.lower()

category_map = {
     'electronics': 'Electronics',
     'clothing': 'Clothing',
      'home & garden': 'Home & Garden',
      'home and garden': 'Home & Garden',
      'sports': 'Sports',
      'books': 'Books',
      'unknown': 'Unknown'
    }

status_map = {
      'delivered' : 'Delivered',
      'pending' : 'Pending',
      'shipped' : 'Shipped',
      'cancelled' : 'Cancelled'
  }

country_map = {
    'united states of america': 'United States', 'usa': 'United States',
    'united states': 'United States', 'us': 'United States',
    'u.s.a': 'United States', 'usa': 'United States',
    'united kingdom': 'United Kingdom', 'uk': 'United Kingdom', 'u.k.': 'United Kingdom',
    'australia': 'Australia', 'aus': 'Australia',
    'canada': 'Canada',
    'germany': 'Germany', 'de': 'Germany',
    'unknown': 'Unknown'
    }

df['category'] = df['category'].map(category_map).fillna(df['category'])
df['status'] = df['status'].map(status_map).fillna(df['status'])
df['country'] = df['country'].map(country_map).fillna(df['country'])

df.head(10)

df['unit_price'] = (
     df['unit_price']
        .astype(str)
        .str.replace(r'[$£,]', '', regex=True)  # commas catch 1,299.00 style values\n",
      .str.strip()
    )
df['unit_price'] = pd.to_numeric(df['unit_price'], errors='coerce')

df.head(10)

#create a dictinory for the replacement with jey value pairs

bool_map = {
        'Yes': True, 'yes': True, 'Y': True, 'y': True,
        'TRUE': True, 'True': True, 'true': True, '1': True, 1: True, True: True,
        'No': False, 'no': False, 'N': False, 'n': False,
       'FALSE': False, 'False': False, 'false': False, '0': False, 0: False, False: False
    }

df['is_returned'] = df['is_returned'].map(bool_map).fillna(False)

df.head(10)

#fixing dates

df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=False, errors='coerce')

failed = df['order_date'].isnull().sum()

df.head(10)

# Extract useful features now that dates are clean


df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_day_of_week'] = df['order_date'].dt.day_name()

print(df[['order_date', 'order_year', 'order_month', 'order_day_of_week']].head())

